### ISSUE TITLE
It would help if there was not so much subclassing

### ISSUE THREAD

**Issue by sumchattering** [appunite/CLCascade#16]

**Comment by emilwojtaszek** [comment]
Just check the example project, only what you have to do is to change: 
UIViewController -> CLViewController
UITableViewController -> CLTableViewController

I thing it is extremely easy! To make it faster use Edit->Refactor or Find->Replace All.

I could not use UINavigationController becouse I've started working on this project before iOS 5 (so there was no properties like childViewControllers and I can't control transitions).

Following this path, I've started using CLNavigationController, so I need to sublass UIViewController to add property of this, to have acces to object which is responding for hierarchy. What more is have ivars which save current state.

I thing inheritance is necessary to deal with all problems, but I could be wrong. If you have a different vision, share it with me, I welcome the opportunity to teach something new.

This project is still in development stage, and feel free to fork and make same pull request to improve this project.

**Comment by ipodishima** [comment]
Hi samyzee

Just to know : will you fork the project to remove all the inheritance stuff ? Because I have the same problem : an iPhone App with controllers, and I just don't want to copy / paste all my controller part code for the iPad. 
In my iPhone App, I already did this for a custom Tab Bar. This is all about categories and associative references, seems that in three20 they don't do like this.

If you won't fork, I do it maybe (depends on the time I have)... Just let me know plz

**Comment by steipete** [comment]
ipodshima, you may wanna check out my stacked view - I looked into CLCascade some time ago but needed a different concept, so I built this: https://github.com/steipete/PSStackedView

**Comment by ipodishima** [comment]
Hi,

I checked out your implementation. Seems to be interesting because you do not need to inherit but there are some things I will need to correct if I use yours :
- the shadow stuff which add over and over on the left
- for me, the panels should not go on top of the menu panel
- there is a glitch in the animation, when you add several panels, and move left / right on a middle panel. The panel on the right is sometimes added with an animation, and this cause the panel on the left to be highlighted.
- we need to add the round corners ourselves

So, I'm not really sure which one of the project I will chose ;)

**Comment by ipodishima** [comment]
Yes maybe. Honestly I'm still thinking because the main problem in CLCascade is the CLViewController. This is the only class I need to move in a category to put my iPhone controllers instead (with some adaptations of course, but easy ones).
The rest of the class can stay like that in my opinion

**Comment by steipete** [comment]
For those issues, it's better to open up issues on my repo.

For the rounded corners - all the code is already there, but deactivated because it needs masking, and this is an absolute performance sucker (it needs offscreen rendering). Thus, it's better to fake the corners yourself.

for the overlay - you could change the z order of the menu items, that shouldn't be so hard.

the shadow stuff is also easily fixable, some code's already there, just didn't had the need to in my project. 

for animations, lots of work went in there, but yes, there's still place for improvements. for my use case, it worked very well.

**Comment by steipete** [comment]
Does CLCascade support view controllers of variable size? Last time I checked there were two fixed sizes.

**Comment by emilwojtaszek** [comment]
Yes, that's true, CLCascade support two sizes:
typedef enum {
    CLViewSizeNormal   = 0,
    CLViewSizeWider    = 1
} CLViewSize;

but you can set this sizes. Calculation is crucial in this framework.
Look at this: http://cl.ly/3v352221030W1t0b2X3r
If you change leftInset, you can change the width of page.

**Comment by emilwojtaszek** [comment]
I came up with a new idea, it will be easier if you replace UIViewController to TTViewController in CLViewController.h.

**Comment by steipete** [comment]
See, my approach calculates all sizes dynamically. No need to restrict it to certain sizes. I just read what size the view controller has when you add it, and use this size. Also supporting dynamic changing of the width (e.g. a smaller max width on portrait mode).

**Comment by emilwojtaszek** [comment]
Great, I guess it took you a lot of time, but I focused on the interface that most resembled that of Twitter.
Maybe in the future I think of similar functionality.
I really need to look into your code ;)

**Comment by emilwojtaszek** [comment]
Let's back to the main thread. Does conversion of a UIViewController to TTViewController comes into play?

**Comment by ipodishima** [comment]
Hi

Right now I'm working on a solution to move the CLViewController to a UIViewController category. I'm close, there are just some issues with the loadView method. By the way, for the CategorieViewController for example, which is loaded from CLTableViewController (this will probably change with my implementation) there is something wrong : why don't you call the [super loadView] method instead of rewriting exactly the same ?

**Comment by ipodishima** [comment]
Did it !

When I will be at home I pull it (network at the office don't work so much).
There will maybe be some stuff to correct / add etc but I'm glad of what I achieved ! I can push any controller I want now
